name: Build the ol-repo-sync image


on:
  workflow_dispatch:
  schedule:
    - cron: '17 6 * * *'
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: djelibeybi/ol-repo-sync


jobs:
  build:
    name: Build ol-repo-sync image

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for newer base image on scheduled runs
        if: github.event_name == 'schedule'
        run: |
          BASE_LAYERS=$(skopeo inspect --config --no-tags docker://ghcr.io/oracle/oraclelinux8-python:3.9-amd64 | jq -r '.rootfs.diff_ids[]')
          REPO_LAYERS=$(skopeo inspect --config --no-tags docker://ghcr.io/djelibeybi/ol-repo-sync:main | jq -r '.rootfs.diff_ids[]')
          if [ -n "${REPO_LAYERS##*$BASE_LAYERS*}" ]; then
            echo "BUILD_IMAGE=YES" >> $GITHUB_ENV
            echo ""
          else
            echo "BUILD_IMAGE=NO" >> $GITHUB_ENV
          fi

      - name: Trigger builds for unscheduled runs
        if: github.event_name != 'schedule'
        run: |
          echo "BUILD_IMAGE=YES" >> $GITHUB_ENV

      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v1.13.1'

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract container metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push container image
        id: build-and-push
        uses: docker/build-push-action@v3
        if: env.BUILD_IMAGE == 'YES'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Sign the published container image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: cosign sign ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build-and-push.outputs.digest }}
